// languages.js
var traduccions = {
    "en": {
        "firma": "VÍCTOR PUCHE",
        "sobremi": "About",
        "micv": "CV",
        "projectes": "Work",
        "contacte": "Contact",
        "hero_pre": "Electronic Engineering",
        "hero_sub": "Embedded systems · Robotics · Automation",
        "btn_connect": "Let’s Connect",
        "btn_cv": "View CV",
        "about_title": "Engineering with intention",
        "about_p": "I’m an Industrial Electronics Engineering student at UPC with hands-on experience in hardware R&D and autonomous robotics. I believe in clean design, robust code, and solutions that endure.",
        "about_cta": "Learn more about my journey →",
        "work_title": "Selected Projects",
        "card1_badge": "Research",
        "card1_title": "Autonomous Coverage Path Planning",
        "card1_p": "Developed CPP algorithms with computer vision localization (ArUco) and polygonal decomposition for unknown environments.",
        "card2_badge": "Industry R&D",
        "card2_title": "Smart Meter Testing Architecture",
        "card2_p": "Automated calibration tests with MODBUS, Grafana dashboards, and LTE integration for solar monitoring.",
        "card3_badge": "Leadership",
        "card3_title": "Faculty Representative & Mentor",
        "card3_p": "Elected student representative managing budgets and bridging startups with university administration.",
        "card4_badge": "Hardware Design",
        "card4_title": "PCB Minipad",
        "card4_p": "Custom mechanical minipad designed from scratch, featuring schematic capture, PCB layout, and embedded firmware programming.",
        "card5_badge": "App Development",
        "card5_title": "Lapis",
        "card5_p": "A modern, collaborative To-Do application built with Flutter and Firebase, featuring real-time syncing and dynamic task management.",
        "contact_title": "Let's Connect",
        "contact_p": "I'm always open to discussing new projects, creative ideas or opportunities to be part of your visions.",
        "btn_email": "vpuche17@gmail.com",
        "btn_linkedin": "LinkedIn",
        "about_page_pre": "Engineer in training · Community leader",
        "about_page_sub": "Industrial Electronics and Automation Engineering Student<br>Financial Secretary · Bachelor and Master Representative at UPC",
        "about_p1": "My name is Víctor Puche i Alonso. I was born in the vibrant city of Barcelona, but currently call Palau-Solità i Plegamans my home, a charming town near the city. I am currently immersed in my studies of Industrial Electronics and Automation Engineering, a discipline that fuels my passion for innovation and technological progress.",
        "about_c1_title": "Community commitment",
        "about_c1_p1": "From a young age, I have felt a strong commitment to my community and its well-being. For the past two years, I have actively participated in various community initiatives, acting as an intermediary between local residents and political authorities to improve everyone's quality of life. Through this, we have successfully engaged citizens during key municipal events.",
        "about_c1_p2": "These experiences have provided me with local and regional contacts, bridging political parties and neighborhood associations to relay citizen concerns directly to the administrations. Currently, I serve as the financial secretary of a neighborhood association, managing funds used for efficient citizen mobilization when necessary.",
        "about_c2_title": "University representation",
        "about_c2_p1": "My commitment to student advocacy was affirmed when I was elected to the University Senate of the Universitat Politècnica de Catalunya—a role I have proudly held for four years. As an independent voice in the chamber, I have consistently worked to bridge the gap between the student body and university administration, ensuring our collective concerns are heard at the highest levels of decision‑making.",
        "about_c3_title": "Empathy and communication",
        "about_c3_p1": "My interest in empathy and effective communication stems from personal experiences, including moments of adversity in my childhood. These events taught me the importance of understanding different perspectives and collaborating to find solutions.",
        "about_c4_title": "Professional philosophy",
        "about_c4_p1": "In the workplace, I firmly believe in creating an inclusive environment where individuals feel valued and can contribute their ideas openly. An organizational culture based on mutual respect and collaboration is essential for the success of any company.",
        "about_c4_p2": "Regarding economics, I am convinced that public-private collaboration can generate powerful synergies driving economic growth and social well-being. I believe in balancing business interests with general societal welfare, as companies ultimately exist to identify and solve societal problems in exchange for a monetary reward.",
        "about_cta_p": "Want to know more about me?",
        "about_cta_link": "Find my CV",
        "about_footer": "Built with Visual Studio and hosted on GitHub: <span class=\"accent\">HTML, CSS and JavaScript – 2024</span>",
        "cv_subhead": "Electronics Engineering Student · Faculty Secretary & Representative",
        "cv_xp_title": "Professional Experience",
        "cv_xp1_title": "Researcher in Autonomous Coverage Robotics",
        "cv_xp1_b1": "Designed and implemented a coverage path planning (CPP) algorithm for autonomous robots in unknown environments, combining exploration and systematic coverage strategies.",
        "cv_xp1_b2": "Developed an exploration framework based on wall-following navigation, enabling online mapping and transformation into structured representations for offline planning.",
        "cv_xp1_b3": "Implemented computer vision localization with ArUco markers, including complete coordinate transformation from image to real world using camera modeling.",
        "cv_xp1_b4": "Built polygonal representations of the environment by sorting detected vertices and calculating enclosed areas for spatial reasoning.",
        "cv_xp1_b5": "Designed a decomposition algorithm to partition irregular areas into rectangular subregions aligned with the robot footprint, optimizing sweeping trajectories.",
        "cv_xp2_title": "Hardware R&D Intern",
        "cv_xp2_b1": "Developed automated testing architecture for high-precision current measurement systems (ANTARES) using MODBUS protocols and MTE reference machines.",
        "cv_xp2_b2": "Created real-time monitoring dashboards with Grafana and InfluxDB for CPU, temperature, and RMS currents on R&D prototypes.",
        "cv_xp2_b3": "Managed the migration and standardization of electronic component libraries from Excel to Altium 365.",
        "cv_xp2_b4": "Performed environmental stress testing programmatically via climate chambers and analyzed battery discharge behaviors using piecewise polynomial modeling.",
        "cv_xp2_b5": "Integrated LTE (4G) connectivity in industrial prototypes for remote solar energy monitoring.",
        "cv_xp2_b6": "Authored technical documentation including FMEAs and operational manuals.",
        "cv_xp3_title": "UPC Entrepreneurship Department Intern",
        "cv_xp3_b1": "Drafted comprehensive reports on departmental fiscal and administrative exercises for the Terrassa City Council and Barcelona Provincial Council.",
        "cv_xp3_b2": "Managed mentoring sessions, meetings, and events acting as a bridge between department coordination and startups.",
        "cv_xp4_title": "Bachelor & Master Student Representative",
        "cv_xp4_b1": "Elected via universal student suffrage among over 5 candidates.",
        "cv_xp4_b2": "Actively participated in university governance sessions and voted on resolutions, including budget allocation.",
        "cv_xp5_title": "Private Physics Tutor (High School)",
        "cv_xp5_b1": "Guided groups of high school seniors in managing coursework to achieve top grades.",
        "cv_xp5_b2": "Prepared postgraduate students for university entrance exams (PAU).",
        "cv_ed_title": "Academic Background",
        "cv_ed1_title": "Bachelor in Mechatronics, Robotics and Automation Engineering (ERASMUS)",
        "cv_ed2_title": "Bachelor in Industrial Electronics and Automation Engineering",
        "cv_ed3_title": "High School (Scientific-Technological pathway)",
        "cv_ed3_date": "Graduated: Jun 2022",
        "cv_skills_title": "Technical Skills",
        "cv_skills_1": "<strong>Languages:</strong> C++, C, Java, HTML, CSS, JavaScript, Assembly, Ladder, ST",
        "cv_skills_2": "<strong>Tools:</strong> Altium 365, SolidWorks, MATLAB, Maple, ROS2 Humble, STM32CubeProgrammer, Grafana, InfluxDB, PowerBI, JIRA",
        "cv_skills_3": "<strong>Protocols/Networks:</strong> MODBUS, TCP/IP, network configuration",
        "cv_skills_4": "<strong>AI & Productivity:</strong> ChatGPT, DeepSeek, Gemini, Copilot",
        "cv_lang_title": "Languages",
        "lang_ca": "Catalan",
        "lang_es": "Spanish",
        "lang_en": "English",
        "lang_de": "German",
        "lang_fr": "French",
        "lvl_native": "Native",
        "lvl_c1": "Very High (C1)",
        "lvl_b1": "Medium (B1)",
        "lvl_basic": "Basic",
        "cv_soft_title": "Personal Competencies",
        "cv_soft_1": "Project management",
        "cv_soft_2": "Effective communication",
        "cv_soft_3": "Research skills",
        "cv_soft_4": "Initiative and autonomy",
        "cv_soft_5": "Leadership and coordination",
        "cv_soft_6": "Empathy and active listening",
        "cv_soft_7": "Discipline under pressure",
        "cv_soft_8": "Adaptability"
    },
    "es": {
        "firma": "VÍCTOR PUCHE",
        "sobremi": "Sobre mí",
        "micv": "CV",
        "projectes": "Proyectos",
        "contacte": "Contacto",
        "hero_pre": "Ingeniería Electrónica",
        "hero_sub": "Sistemas embebidos · Robótica · Automatización",
        "btn_connect": "Conectemos",
        "btn_cv": "Ver CV",
        "about_title": "Ingeniería con intención",
        "about_p": "Soy estudiante de Ingeniería Electrónica Industrial en la UPC con experiencia práctica en I+D de hardware y robótica autónoma. Creo en el diseño limpio, el código robusto y las soluciones duraderas.",
        "about_cta": "Descubre más sobre mi trayectoria →",
        "work_title": "Proyectos Destacados",
        "card1_badge": "Investigación",
        "card1_title": "Planificación de Cobertura Autónoma",
        "card1_p": "Desarrollé algoritmos CPP con localización por visión artificial (ArUco) y descomposición poligonal en entornos desconocidos.",
        "card2_badge": "I+D Industrial",
        "card2_title": "Arquitectura de Pruebas de Contadores Inteligentes",
        "card2_p": "Pruebas de calibración automatizadas con MODBUS, paneles en Grafana e integración LTE para monotorización solar.",
        "card3_badge": "Liderazgo",
        "card3_title": "Representante de Facultad y Mentor",
        "card3_p": "Representante de estudiantes electo gestionando presupuestos y tendiendo puentes entre startups y la administración de la universidad.",
        "card4_badge": "Diseño de Hardware",
        "card4_title": "PCB Minipad",
        "card4_p": "Minipad mecánico personalizado diseñado desde cero, con captura de esquemas, diseño de PCB y programación de firmware.",
        "card5_badge": "Desarrollo de Apps",
        "card5_title": "Lapis",
        "card5_p": "Una aplicación de listas de tareas moderna y colaborativa creada con Flutter y Firebase, con sincronización en tiempo real y gestión dinámica de tareas.",
        "contact_title": "Conectemos",
        "contact_p": "Siempre estoy abierto a discutir nuevos proyectos, ideas creativas u oportunidades para formar part de tus visiones.",
        "btn_email": "vpuche17@gmail.com",
        "btn_linkedin": "LinkedIn",
        "about_page_pre": "Ingeniero en formación · Líder comunitario",
        "about_page_sub": "Estudiante de Ingeniería Electrónica Industrial y Automática<br>Secretario de Finanzas · Representante de Grado y Máster en la UPC",
        "about_p1": "Me llamo Víctor Puche i Alonso. Nací en la vibrante ciudad de Barcelona, pero actualmente considero mi hogar a Palau-Solità i Plegamans, un encantador pueblo situado cerca de la ciudad condal. En la actualidad, estoy inmerso en mis estudios de Ingeniería Electrónica Industrial y Automática, una disciplina que despierta mi pasión por la innovación y el progreso tecnológico.",
        "about_c1_title": "Compromiso comunitario",
        "about_c1_p1": "Desde joven, he sentido un fuerte compromiso con mi comunidad y su bienestar. Desde hace dos años, he participado activamente en diversas iniciativas comunitarias, actuando como intermediario entre los residentes locales y las autoridades políticas, con el objetivo de mejorar la calidad de vida de todos. Gracias a esto, hemos podido movilizar a la ciudadanía sobre todo en eventos clave del municipio.",
        "about_c1_p2": "Estas experiencias también me han proporcionado contactos a nivel local y regional, gracias a las relaciones entre los partidos políticos y asociaciones vecinales, para trasladar las preocupaciones directamente a las administraciones. Actualmente soy el secretario de finanzas de una asociación, gestionando los fondos usados para la movilización ciudadana cuando es necesario.",
        "about_c2_title": "Representación universitaria",
        "about_c2_p1": "Recientemente tuve el honor de ser elegido para representar a los estudiantes en el claustro de la Universitat Politècnica de Catalunya. Me presenté como candidato independiente y gané mi representación parlamentaria gracias al apoyo de mis compañeros. Esta oportunidad me permite participar activamente en la toma de decisiones universitarias y defender nuestros intereses.",
        "about_c3_title": "Empatía y comunicación",
        "about_c3_p1": "Mi interés por la empatía y la comunicación efectiva proviene de experiencias personales, incluyendo momentos de adversidad en mi infancia. Estos eventos me han enseñado la importancia de comprender distintas perspectivas y trabajar en colaboración para encontrar soluciones.",
        "about_c4_title": "Filosofía profesional",
        "about_c4_p1": "En el entorno laboral, creo firmemente en la creación de un ambiente inclusivo donde cada individuo se sienta valorado y pueda contribuir con sus ideas abierta y libremente. Mantengo que una cultura organizacional basada en el respeto mutuo y la colaboración es esencial para el éxito.",
        "about_c4_p2": "En cuanto a economía, estoy convencido de que la colaboración público-privada puede generar poderosas sinergias que impulsen el crecimiento económico y el bienestar social. Creo en equilibrar los intereses empresariales con el bienestar social general, ya que las empresas existen fundamentalmente para identificar y solucionar los problemas de la población a cambio de retribución monetaria.",
        "about_cta_p": "¿Te animas a saber más de mí?",
        "about_cta_link": "Encuentra mi CV",
        "about_footer": "Creado con Visual Studio y alojado en GitHub: <span class=\"accent\">HTML, CSS y JavaScript – 2024</span>",
        "cv_subhead": "Estudiante de Ingeniería Electrónica · Secretario y Representante de Facultad",
        "cv_xp_title": "Experiencia Profesional",
        "cv_xp1_title": "Investigador en Robótica de Cobertura Autónoma",
        "cv_xp1_b1": "Diseñé e implementé un algoritmo de planificación de cobertura (CPP) para robots autónomos en entornos desconocidos, combinando estrategias de exploración y cobertura sistemática.",
        "cv_xp1_b2": "Desarrollé un marco de exploración basado en navegación por seguimiento de paredes, permitiendo el mapeo en línea y su transformación en una representación estructurada para planificación offline.",
        "cv_xp1_b3": "Implementé localización basada en visión por computador con marcadores ArUco, incluyendo transformación completa de coordenadas de imagen a mundo real mediante modelado de cámara.",
        "cv_xp1_b4": "Construí representaciones poligonales del entorno ordenando vértices detectados y calculando áreas cerradas para razonamiento espacial.",
        "cv_xp1_b5": "Diseñé un algoritmo de descomposición para particionar áreas irregulares en subregiones rectangulares alineadas con la huella del robot, optimizando trayectorias de barrido.",
        "cv_xp2_title": "Becario de I+D en Hardware",
        "cv_xp2_b1": "Desarrollé una arquitectura de pruebas automatizadas para sistemas de medición de corriente de alta precisión (ANTARES) usando protocolos MODBUS y máquinas de referencia MTE.",
        "cv_xp2_b2": "Creé paneles de monitorización en tiempo real con Grafana e InfluxDB para CPU, temperatura y corrientes RMS de múltiples prototipos de I+D.",
        "cv_xp2_b3": "Gestioné la migración y estandarización de librerías de componentes electrónicos de Excel a Altium 365.",
        "cv_xp2_b4": "Realicé pruebas de estrés ambiental programando cámaras climáticas y analizando comportamientos de descarga de baterías mediante modelado polinómico por tramos.",
        "cv_xp2_b5": "Integré conectividad LTE (4G) en prototipos industriales para monitorización remota de energía solar.",
        "cv_xp2_b6": "Redacté documentación técnica incluyendo AMFE y manuales operativos.",
        "cv_xp3_title": "Becario del Departamento de Emprendimiento UPC",
        "cv_xp3_b1": "Elaboré un informe sobre todos los ejercicios fiscales y administrativos del departamento para el Ayuntamiento de Terrassa y la Diputación de Barcelona.",
        "cv_xp3_b2": "Gestioné sesiones de mentoría, reuniones y eventos como puente entre la coordinación del departamento y las startups.",
        "cv_xp4_title": "Representante de Estudiantes de Grado y Máster",
        "cv_xp4_b1": "Elegido por sufragio universal estudiantil entre más de 5 candidatos.",
        "cv_xp4_b2": "Participé activamente en sesiones de gobierno universitario y voté resoluciones, incluyendo asignación de presupuestos.",
        "cv_xp5_title": "Profesor Particular de Física (Bachillerato)",
        "cv_xp5_b1": "Ayudé a grupos de estudiantes de segundo de bachillerato a gestionar su carga lectiva para obtener las mejores calificaciones posibles.",
        "cv_xp5_b2": "Preparé a estudiantes post-graduados para sus exámenes de acceso a la universidad (PAU).",
        "cv_ed_title": "Formación Académica",
        "cv_ed1_title": "Grado en Ingeniería Mecatrónica, Robótica y Automatización (ERASMUS)",
        "cv_ed2_title": "Grado en Ingeniería Electrónica Industrial y Automática",
        "cv_ed3_title": "Bachillerato (Modalidad Científico-Tecnológica)",
        "cv_ed3_date": "Graduado: Jun 2022",
        "cv_skills_title": "Habilidades Técnicas",
        "cv_skills_1": "<strong>Lenguajes:</strong> C++, C, Java, HTML, CSS, JavaScript, Assembly, Ladder, ST",
        "cv_skills_2": "<strong>Herramientas:</strong> Altium 365, SolidWorks, MATLAB, Maple, ROS2 Humble, STM32CubeProgrammer, Grafana, InfluxDB, PowerBI, JIRA",
        "cv_skills_3": "<strong>Protocolos/Redes:</strong> MODBUS, TCP/IP, configuración de redes",
        "cv_skills_4": "<strong>IA & Productividad:</strong> ChatGPT, DeepSeek, Gemini, Copilot",
        "cv_lang_title": "Idiomas",
        "lang_ca": "Catalán",
        "lang_es": "Español",
        "lang_en": "Inglés",
        "lang_de": "Alemán",
        "lang_fr": "Francés",
        "lvl_native": "Nativo",
        "lvl_c1": "Muy Alto (C1)",
        "lvl_b1": "Medio (B1)",
        "lvl_basic": "Básico",
        "cv_soft_title": "Competencias Personales",
        "cv_soft_1": "Gestión de proyectos",
        "cv_soft_2": "Comunicación efectiva",
        "cv_soft_3": "Capacidad de investigación",
        "cv_soft_4": "Iniciativa y autonomía",
        "cv_soft_5": "Liderazgo y coordinación",
        "cv_soft_6": "Empatía y escucha activa",
        "cv_soft_7": "Disciplina bajo presión",
        "cv_soft_8": "Adaptabilidad"
    },
    "ca": {
        "firma": "VÍCTOR PUCHE",
        "sobremi": "Sobre mi",
        "micv": "CV",
        "projectes": "Projectes",
        "contacte": "Contacte",
        "hero_pre": "Enginyeria Electrònica",
        "hero_sub": "Sistemes incrustats · Robòtica · Automatització",
        "btn_connect": "Connectem",
        "btn_cv": "Veure CV",
        "about_title": "Enginyeria amb intenció",
        "about_p": "Sóc estudiant d'Enginyeria Electrònica Industrial a la UPC amb experiència pràctica en R+D de maquinari i robòtica autònoma. Crec en el disseny net, el codi robust i les solucions duradores.",
        "about_cta": "Descobreix més sobre la meva trajectòria →",
        "work_title": "Projectes Destacats",
        "card1_badge": "Recerca",
        "card1_title": "Planificació de Cobertura Autònoma",
        "card1_p": "Vaig desenvolupar algorismes CPP amb localització per visió per computador (ArUco) i descomposició poligonal en entorns desconeguts.",
        "card2_badge": "R+D Industrial",
        "card2_title": "Arquitectura de Proves de Comptadors Intel·ligents",
        "card2_p": "Proves de calibratge automatitzades amb MODBUS, panells en Grafana i integració LTE per al monitoratge solar.",
        "card3_badge": "Lideratge",
        "card3_title": "Representant de Facultat i Mentor",
        "card3_p": "Representant d'estudiants electe gestionant pressupostos i establint ponts entre startups i l'administració de la universitat.",
        "card4_badge": "Disseny de Maquinari",
        "card4_title": "PCB Minipad",
        "card4_p": "Minipad mecànic personalitzat dissenyat des de zero, amb captura d'esquemes, disseny de PCB i programació de firmware.",
        "card5_badge": "Desenvolupament d'Apps",
        "card5_title": "Lapis",
        "card5_p": "Una aplicació moderna i col·laborativa de llistes de tasques creada amb Flutter i Firebase, amb sincronització en temps real i gestió dinàmica de tasques.",
        "contact_title": "Connectem",
        "contact_p": "Sempre estic obert a discutir nous projectes, idees creatives o oportunitats per formar part de les teves visions.",
        "btn_email": "vpuche17@gmail.com",
        "btn_linkedin": "LinkedIn",
        "about_page_pre": "Enginyer en formació · Líder comunitari",
        "about_page_sub": "Estudiant d'Enginyeria Electrònica Industrial i Automàtica<br>Secretari de Finances · Representant de Grau i Màster a la UPC",
        "about_p1": "Em dic Víctor Puche i Alonso. Vaig néixer a la vibrant ciutat de Barcelona, però actualment considero la meva llar a Palau-Solità i Plegamans, un encantador poble situat prop de la ciutat comtal. En l'actualitat, estic immers en els meus estudis d'Enginyeria Electrònica Industrial i Automàtica, una disciplina que desperta la meva passió per la innovació i el progrés tecnològic.",
        "about_c1_title": "Compromís comunitari",
        "about_c1_p1": "De jove, he sentit un fort compromís amb la meva comunitat i el seu benestar. Des de fa dos anys, he participat activament en diverses iniciatives comunitàries, actuant com a intermediari entre els residents locals i les autoritats polítiques, amb l'objectiu de millorar la qualitat de vida de tots. Gràcies a això, hem pogut mobilitzar la ciutadania sobretot en esdeveniments clau del municipi.",
        "about_c1_p2": "Aquestes experiències també m'han proporcionat contactes a nivell local i regional, gràcies a les relacions entre els partits polítics i associacions veïnals, per poder traslladar les preocupacions directament a les administracions. Actualment sóc el secretari de finances d'una associació, gestionant els fons utilitzats per a la mobilització ciutadana quan és necessari.",
        "about_c2_title": "Representació universitària",
        "about_c2_p1": "Recentment vaig tenir l'honor de ser escollit per representar els estudiants al claustre de la Universitat Politècnica de Catalunya. Em vaig presentar com a candidat independent i vaig guanyar la meva representació parlamentària gràcies al suport dels meus companys. Aquesta oportunitat em permet participar activament en la presa de decisions universitàries i defensar els nostres interessos.",
        "about_c3_title": "Empatia i comunicació",
        "about_c3_p1": "El meu interès per l'empatia i la comunicació efectiva prové d'experiències personals, incloent-hi moments d'adversitat en la meva infància. Aquests esdeveniments m'han ensenyat la importància de comprendre diferents perspectives i treballar en col·laboració per trobar solucions.",
        "about_c4_title": "Filosofia professional",
        "about_c4_p1": "En l'entorn laboral, crec fermament en la creació d'un ambient inclusiu on cada individu se senti valorat i pugui contribuir amb les seves idees obertament i lliurement. Mantinc que una cultura organitzacional basada en el respecte mutu i la col·laboració és essencial per a l'èxit.",
        "about_c4_p2": "Pel que fa a l'economia, estic convençut que la col·laboració publicoprivada pot generar poderoses sinergies que impulsin el creixement econòmic i el benestar social. Crec en equilibrar els interessos empresarials amb el benestar social general, ja que les empreses existeixen fonamentalment per identificar i solucionar els problemes de la població a canvi d'una retribució monetària.",
        "about_cta_p": "T'animes a saber més de mi?",
        "about_cta_link": "Troba el meu CV",
        "about_footer": "Creat amb Visual Studio i allotjat a GitHub: <span class=\"accent\">HTML, CSS i JavaScript – 2024</span>",
        "cv_subhead": "Estudiant d'Enginyeria Electrònica · Secretari i Representant de Facultat",
        "cv_xp_title": "Experiència Professional",
        "cv_xp1_title": "Investigador en Robòtica de Cobertura Autònoma",
        "cv_xp1_b1": "Vaig dissenyar i implementar un algorisme de planificació de cobertura (CPP) per a robots autònoms en entorns desconeguts, combinant estratègies d'exploració i cobertura sistemàtica.",
        "cv_xp1_b2": "Vaig desenvolupar un marc d'exploració basat en navegació per seguiment de parets, permetent el mapatge en línia i la seva transformació en una representació estructurada per a planificació offline.",
        "cv_xp1_b3": "Vaig implementar localització basada en visió per computador amb marcadors ArUco, incloent-hi la transformació completa de coordenades d'imatge a món real mitjançant modelatge de càmera.",
        "cv_xp1_b4": "Vaig construir representacions poligonals de l'entorn ordenant vèrtexs detectats i calculant àrees tancades per al raonament espacial.",
        "cv_xp1_b5": "Vaig dissenyar un algorisme de descomposició per particionar àrees irregulars en subregions rectangulars alineades amb la petjada del robot, optimitzant trajectòries d'escombrat.",
        "cv_xp2_title": "Becari d'R+D en Maquinari",
        "cv_xp2_b1": "Vaig desenvolupar una arquitectura de proves automatitzades per a sistemes de mesura de corrent d'alta precisió (ANTARES) usant protocols MODBUS i màquines de referència MTE.",
        "cv_xp2_b2": "Vaig crear panells de monitoratge en temps real amb Grafana i InfluxDB per a CPU, temperatura i corrents RMS de múltiples prototips d'R+D.",
        "cv_xp2_b3": "Vaig gestionar la migració i estandardització de llibreries de components electrònics d'Excel a Altium 365.",
        "cv_xp2_b4": "Vaig realitzar proves d'estrès ambiental programant cambres climàtiques i analitzant comportaments de descàrrega de bateries mitjançant modelatge polinòmic per trams.",
        "cv_xp2_b5": "Vaig integrar connectivitat LTE (4G) en prototips industrials per al monitoratge remot d'energia solar.",
        "cv_xp2_b6": "Vaig redactar documentació tècnica incloent-hi AMFE i manuals operatius.",
        "cv_xp3_title": "Becari del Departament d'Emprenedoria UPC",
        "cv_xp3_b1": "Vaig elaborar un informe sobre tots els exercicis fiscals i administratius del departament per a l'Ajuntament de Terrassa i la Diputació de Barcelona.",
        "cv_xp3_b2": "Vaig gestionar sessions de mentoria, reunions i esdeveniments com a pont entre la coordinació del departament i les startups.",
        "cv_xp4_title": "Representant d'Estudiants de Grau i Màster",
        "cv_xp4_b1": "Escollit per sufragi universal estudiantil entre més de 5 candidats.",
        "cv_xp4_b2": "Vaig participar activament en sessions de govern universitari i vaig votar resolucions, incloent-hi l'assignació de pressupostos.",
        "cv_xp5_title": "Professor Particular de Física (Batxillerat)",
        "cv_xp5_b1": "Vaig ajudar grups d'estudiants de segon de batxillerat a gestionar la seva càrrega lectiva per obtenir les millors qualificacions possibles.",
        "cv_xp5_b2": "Vaig preparar estudiants postgraduats per als seus exàmens d'accés a la universitat (PAU).",
        "cv_ed_title": "Formació Acadèmica",
        "cv_ed1_title": "Grau en Enginyeria Mecatrònica, Robòtica i Automatització (ERASMUS)",
        "cv_ed2_title": "Grau en Enginyeria Electrònica Industrial i Automàtica",
        "cv_ed3_title": "Batxillerat (Modalitat Cientificotecnològica)",
        "cv_ed3_date": "Graduat: Juny 2022",
        "cv_skills_title": "Habilitats Tècniques",
        "cv_skills_1": "<strong>Llenguatges:</strong> C++, C, Java, HTML, CSS, JavaScript, Assembly, Ladder, ST",
        "cv_skills_2": "<strong>Eines:</strong> Altium 365, SolidWorks, MATLAB, Maple, ROS2 Humble, STM32CubeProgrammer, Grafana, InfluxDB, PowerBI, JIRA",
        "cv_skills_3": "<strong>Protocols/Xarxes:</strong> MODBUS, TCP/IP, configuració de xarxes",
        "cv_skills_4": "<strong>IA i Productivitat:</strong> ChatGPT, DeepSeek, Gemini, Copilot",
        "cv_lang_title": "Idiomes",
        "lang_ca": "Català",
        "lang_es": "Espanyol",
        "lang_en": "Anglès",
        "lang_de": "Alemany",
        "lang_fr": "Francès",
        "lvl_native": "Natiu",
        "lvl_c1": "Molt Alt (C1)",
        "lvl_b1": "Mitjà (B1)",
        "lvl_basic": "Bàsic",
        "cv_soft_title": "Competències Personals",
        "cv_soft_1": "Gestió de projectes",
        "cv_soft_2": "Comunicació efectiva",
        "cv_soft_3": "Capacitat de recerca",
        "cv_soft_4": "Iniciativa i autonomia",
        "cv_soft_5": "Lideratge i coordinació",
        "cv_soft_6": "Empatia i escolta activa",
        "cv_soft_7": "Disciplina sota pressió",
        "cv_soft_8": "Adaptabilitat"
    },
    "de": {
        "firma": "VÍCTOR PUCHE",
        "sobremi": "Über mich",
        "micv": "Lebenslauf",
        "projectes": "Projekte",
        "contacte": "Kontakt",
        "hero_pre": "Elektronik-Ingenieurwesen",
        "hero_sub": "Eingebettete Systeme · Robotik · Automatisierung",
        "btn_connect": "Vernetzen",
        "btn_cv": "Lebenslauf",
        "about_title": "Technik mit Absicht",
        "about_p": "Ich bin Student der Industrieelektronik an der UPC mit praktischer Erfahrung in Hardware-F&E und autonomer Robotik. Ich glaube an klares Design, robusten Code und dauerhafte Lösungen.",
        "about_cta": "Erfahren Sie mehr über meinen Weg →",
        "work_title": "Ausgewählte Projekte",
        "card1_badge": "Forschung",
        "card1_title": "Autonome Coverage-Pfadplanung",
        "card1_p": "Entwicklung von CPP-Algorithmen mit Computer-Vision-Lokalisierung (ArUco) und polygonaler Zerlegung für unbekannte Umgebungen.",
        "card2_badge": "Industrie-F&E",
        "card2_title": "Smart-Meter-Testarchitektur",
        "card2_p": "Automatisierte Kalibrierungstests mit MODBUS, Grafana-Dashboards und LTE-Integration für die Solarüberwachung.",
        "card3_badge": "Führung",
        "card3_title": "Fakultätsvertreter & Mentor",
        "card3_p": "Gewählter Studentenvertreter, Verwaltung von Budgets und Bindeglied zwischen Start-ups und der Universitätsverwaltung.",
        "card4_badge": "Hardware-Design",
        "card4_title": "PCB Minipad",
        "card4_p": "Kundenindividuelles mechanisches Minipad von Grund auf entworfen, inklusive Schaltplanerstellung, PCB-Layout und Firmware.",
        "card5_badge": "App-Entwicklung",
        "card5_title": "Lapis",
        "card5_p": "Eine moderne, kollaborative To-Do-Anwendung, die mit Flutter und Firebase erstellt wurde und Echtzeit-Synchronisation sowie dynamisches Aufgabenmanagement bietet.",
        "contact_title": "Lassen Sie uns vernetzen",
        "contact_p": "Ich bin immer offen für Gespräche über neue Projekte, kreative Ideen oder Möglichkeiten, Teil Ihrer Visionen zu sein.",
        "btn_email": "vpuche17@gmail.com",
        "btn_linkedin": "LinkedIn",
        "about_page_pre": "Ingenieur in Ausbildung · Gemeindevorsteher",
        "about_page_sub": "Student der Industrieelektronik und Automatisierungstechnik<br>Finanzsekretär · Bachelor- und Master-Vertreter an der UPC",
        "about_p1": "Mein Name ist Víctor Puche i Alonso. Ich wurde in der pulsierenden Stadt Barcelona geboren, betrachte aber derzeit Palau-Solità i Plegamans als mein Zuhause, eine charmante Stadt in der Nähe. Ich vertiefe mich derzeit in mein Studium der Industrieelektronik und Automatisierungstechnik, eine Disziplin, die meine Leidenschaft für Innovation weckt.",
        "about_c1_title": "Gemeinschaftliches Engagement",
        "about_c1_p1": "Seit meiner Jugend empfinde ich ein starkes Engagement für meine Gemeinde. In den letzten zwei Jahren habe ich aktiv an verschiedenen Initiativen teilgenommen und als Vermittler zwischen Anwohnern und Behörden gewirkt.",
        "about_c1_p2": "Diese Erfahrungen haben mir lokale Kontakte beschert. Derzeit bin ich als Finanzsekretär einer Nachbarschaftsvereinigung tätig.",
        "about_c2_title": "Universitäre Vertretung",
        "about_c2_p1": "Kürzlich hatte ich die Ehre, gewählt zu werden, um Studenten an der Universitat Politècnica de Catalunya zu vertreten. Diese Gelegenheit ermöglicht es mir, aktiv an Entscheidungen der Universität teilzunehmen.",
        "about_c3_title": "Empathie und Kommunikation",
        "about_c3_p1": "Mein Interesse an Empathie und effektiver Kommunikation rührt aus persönlichen Erfahrungen. Diese Ereignisse lehrten mich, wie wichtig es ist, verschiedene Perspektiven zu verstehen.",
        "about_c4_title": "Berufliche Philosophie",
        "about_c4_p1": "Am Arbeitsplatz glaube ich fest daran, ein integratives Umfeld zu schaffen, in dem sich jeder wertgeschätzt fühlt. Eine Organisationskultur, die auf gegenseitigem Respekt basiert, ist entscheidend.",
        "about_c4_p2": "In Bezug auf die Wirtschaft bin ich davon überzeugt, dass die Zusammenarbeit von öffentlichem und privatem Sektor starke Synergien erzeugen kann, die das Wirtschaftswachstum und das soziale Wohlergehen fördern.",
        "about_cta_p": "Möchten Sie mehr über mich erfahren?",
        "about_cta_link": "Finden Sie meinen Lebenslauf",
        "about_footer": "Erstellt mit Visual Studio und gehostet auf GitHub: <span class=\"accent\">HTML, CSS und JavaScript – 2024</span>",
        "cv_subhead": "Student der Elektronik · Fakultätssekretär & Vertreter",
        "cv_xp_title": "Berufserfahrung",
        "cv_xp1_title": "Forscher für autonome Coverage-Robotik",
        "cv_xp1_b1": "Entwicklung und Implementierung eines CPP-Algorithmus für autonome Roboter in unbekannten Umgebungen.",
        "cv_xp1_b2": "Entwicklung eines Explorations-Frameworks basierend auf Wandfolge-Navigation.",
        "cv_xp1_b3": "Implementierung von Computer-Vision-Lokalisierung mit ArUco-Markern.",
        "cv_xp1_b4": "Erstellung polygonaler Darstellungen der Umgebung durch Sortierung erkannter Eckpunkte.",
        "cv_xp1_b5": "Entwurf eines Zerlegungsalgorithmus zur Partitionierung unregelmäßiger Bereiche in rechteckige Teilregionen.",
        "cv_xp2_title": "Praktikant im Bereich Hardware-F&E",
        "cv_xp2_b1": "Entwicklung einer automatisierten Testarchitektur für hochpräzise Strommesssysteme.",
        "cv_xp2_b2": "Erstellung von Echtzeit-Überwachungs-Dashboards mit Grafana und InfluxDB.",
        "cv_xp2_b3": "Verwaltung der Migration von elektronischen Komponenten-Bibliotheken zu Altium 365.",
        "cv_xp2_b4": "Durchführung von Umweltstresstests über Klimakammern.",
        "cv_xp2_b5": "Integration von LTE (4G)-Konnektivität in industrielle Prototypen für die Solarüberwachung.",
        "cv_xp2_b6": "Verfassung technischer Dokumentationen.",
        "cv_xp3_title": "Praktikant der UPC Entrepreneurship Abteilung",
        "cv_xp3_b1": "Erstellung umfassender Berichte über die finanziellen und administrativen Aufgaben der Abteilung.",
        "cv_xp3_b2": "Leitung von Mentoring-Sitzungen und Meetings als Bindeglied zwischen Startups und Verwaltung.",
        "cv_xp4_title": "Studentenvertreter im Bachelor & Master",
        "cv_xp4_b1": "Gewählt durch allgemeines Studentenwahlrecht unter mehr als 5 Kandidaten.",
        "cv_xp4_b2": "Aktive Teilnahme an Sitzungen der Universitätsleitung.",
        "cv_xp5_title": "Privater Physik-Nachhilfelehrer",
        "cv_xp5_b1": "Betreuung von Oberstufenschülern zur Erzielung von Bestnoten.",
        "cv_xp5_b2": "Vorbereitung von Studenten auf Hochschulaufnahmeprüfungen.",
        "cv_ed_title": "Akademischer Hintergrund",
        "cv_ed1_title": "Bachelor in Mechatronik, Robotik und Automatisierungstechnik (ERASMUS)",
        "cv_ed2_title": "Bachelor in Industrieelektronik und Automatisierungstechnik",
        "cv_ed3_title": "Abitur (Wissenschaftlich-Technologischer Zweig)",
        "cv_ed3_date": "Abschluss: Juni 2022",
        "cv_skills_title": "Technische Fähigkeiten",
        "cv_skills_1": "<strong>Sprachen:</strong> C++, C, Java, HTML, CSS, JavaScript, Assembly, Ladder, ST",
        "cv_skills_2": "<strong>Werkzeuge:</strong> Altium 365, MATLAB, ROS2, Grafana, InfluxDB, PowerBI",
        "cv_skills_3": "<strong>Protokolle:</strong> MODBUS, TCP/IP",
        "cv_skills_4": "<strong>KI:</strong> ChatGPT, DeepSeek, Gemini",
        "cv_lang_title": "Sprachen",
        "lang_ca": "Katalanisch",
        "lang_es": "Spanisch",
        "lang_en": "Englisch",
        "lang_de": "Deutsch",
        "lang_fr": "Französisch",
        "lvl_native": "Muttersprache",
        "lvl_c1": "Sehr gut (C1)",
        "lvl_b1": "Mittel (B1)",
        "lvl_basic": "Grundkenntnisse",
        "cv_soft_title": "Persönliche Kompetenzen",
        "cv_soft_1": "Projektmanagement",
        "cv_soft_2": "Effektive Kommunikation",
        "cv_soft_3": "Forschungskompetenz",
        "cv_soft_4": "Initiative",
        "cv_soft_5": "Führung",
        "cv_soft_6": "Empathie",
        "cv_soft_7": "Belastbarkeit",
        "cv_soft_8": "Anpassungsfähigkeit"
    }
};

function canviaIdioma() {
    var sels = document.querySelectorAll(".seleccioidioma");
    if (sels.length === 0) return;

    // Attempt to get context from the changed dropdown, or fallback to first
    var idiomaSeleccionat = sels[0].value;
    // Actually we should trigger from the specific event to know which value, 
    // but a global function canviaIdioma() called onChange often pulls from standard class

    // Because there could be multiple selectors, let's grab the value of the targeted one
    // But since they are all identical, using sels[0] is often fine unless it's out of sync
    // Wait, onchange="canviaIdioma()" isn't passing 'this'. Let's find the active one:
    var activeSelValue = (event && event.target && event.target.value) ? event.target.value : sels[0].value;
    idiomaSeleccionat = activeSelValue;

    // Persist English as default or standard user pref across tabs
    localStorage.setItem('lang', idiomaSeleccionat);

    // Sync all
    sels.forEach(function (s) { s.value = idiomaSeleccionat; });

    var keys = Object.keys(traduccions[idiomaSeleccionat] || {});
    for (var i = 0; i < keys.length; i++) {
        var key = keys[i];
        var text = traduccions[idiomaSeleccionat][key];

        // by ID
        var elem = document.getElementById(key);
        if (elem) {
            elem.innerHTML = text;
        }

        // by data-i18n attribute
        var elements = document.querySelectorAll('[data-i18n="' + key + '"]');
        elements.forEach(function (el) {
            el.innerHTML = text;
        });
    }
}

window.addEventListener('DOMContentLoaded', () => {
    var savedLang = localStorage.getItem('lang') || 'en';
    var selects = document.querySelectorAll(".seleccioidioma");
    selects.forEach(s => s.value = savedLang);
    canviaIdioma();
});